config/routes.rb
FlashLife::Application.routes.draw do

  resources :users
  resources :events
  resources :uploads

  resource :session, only:[:new, :create, :destroy]

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :user

	has_many :uploads
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	belongs_to :event

	has_attached_file :uploaded_file,  styles: { original: "800x538>", originalv: "404x600>", small: "400x269>", smallv: "202x300>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :uploaded_file, :content_type =>/\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	include ActiveModel::SecurePassword
	has_many :events
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

	def current_user
  		@current_user ||=User.find(session[:user_id]) if session[:user_id]
	end

  	helper_method :current_user

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @user = User.find(session[:user_id])
    @event = Event.find(params[:id])
  end

  def new
    @user = User.find(session[:user_id])
    @event = Event.new
  end

  def create
    @user = User.find(session[:user_id])
    @event = Event.new(event_params)
    
    if @event.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      redirect_to event_path(@event)
    else
      render 'edit' 
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy 
    redirect_to user_path(@user)
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :is_public, :location, :package_type, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		# Present an empty login form
		@user = User.new
	end

	def create
		# Find the user that is trying to log in		
		@user = User.where(email: params[:user][:email]).first
		if @user && @user.authenticate(params[:user][:password])
			# Store as a cookie in the users' browser the ID of them,
			# indicating that they are logged in
			session[:user_id] = @user.id.to_s
			redirect_to user_path(@user.id)
		else
			# Go back to the login page
			redirect_to new_session_path
		end
	end

	def destroy
		reset_session
		redirect_to root_path
	end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.create(upload_params)
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params[:upload].permit(:uploaded_file, :event_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to user_path(@user.id)
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@event = Event.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_path(@user.id)
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		session[:user_id] = nil if session[:user_id] == @user.id
		@user.destroy
		redirect_to root_path
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :address, :phone_number)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = User.new
  	@business = Yelp.client.business('flash-life-photo-booth-rental-los-angeles')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <div class="field">
    <%= f.label "Event Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Event Date" %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label "Location" %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label "Package Type" %>
    <%= f.select :package_type, options_for_select(["Flashy Booth", "Action Booth", "Red Carpet Event", "A-List Red Carpet"]), :selected => params[:package_type] %><br />
  </div>
  <div class="field">
    <%= f.label "Make Gallery Public"%><br>
    <%= f.check_box(:is_public, {}, true) %><br>
  </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
   <%= f.submit @button_face, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<body class="event-background">

<h1>Edit Event</h1>

<%= render 'form' %>
</body>

app/views/events/index.html.erb
<body>
  <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <% if current_user %>
                    <%= link_to "WELCOME" + " #{current_user.first_name.upcase}", user_path(current_user) %>
                <% else %>
                    <a href="#top">FLASH LIFE PHOTO BOOTH</a>
                <% end %>
            </li>
            <% if current_user %>
                <li>
                    <%= link_to "SIGN OUT", session_path, method: :delete %>
                </li>
            <% else %>
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">SIGN IN <strong class="caret"></strong></a>
                    <div class="dropdown-menu" style="padding: 15px; padding-bottom: 10px;">
                        <%= form_for(@user, {url: session_path}) do |f| %>
                            <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
                            <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
                            <%= f.submit "Sign In", class: "btn btn-dark" %>
                        <% end %>
                    </div>
                </li>
            <% end %>
        </ul>
    </nav>

<header class="header">
  <div class="container-fluid"> 
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">

        <h2>ALL EVENTS</h2>
        <div class="table-responsive table-condensed">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>User Id</th>
                <th>Name</th>
                <th>Date</th>
                <th>Location</th>
                <th>Package Type</th>
                <th>Album ID</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @events.each do |event| %>
                <tr>
                  <td><%= event.user_id %></td>
                  <td><%= event.name %></td>
                  <td><%= event.date %></td>
                  <td><%= event.location %></td>
                  <td><%= event.package_type %></td>
                  <td><%= link_to 'Show', event %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <br>
        </div>
      </div>
    </div>
  </div>

</header>
<script>
// Closes the sidebar menu
$("#menu-close").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Opens the sidebar menu
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Scrolls to the selected menu item on the page
$(function() {
    $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html,body').animate({
                    scrollTop: target.offset().top
                }, 1000);
                return false;
            }
        }
    });
});
</script>
</body>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>
</body>

app/views/events/show.html.erb
<body> 
 
 <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <% if current_user %>
                    <%= link_to "WELCOME" + " #{current_user.first_name.upcase}", user_path(current_user) %>
                <% else %>
                    <a href="#top">FLASH LIFE PHOTO BOOTH</a>
                <% end %>
            </li>
            <li class"dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">EDIT EVENT<strong class="caret"></strong></a>
                <div class="dropdown-menu" style="padding: 15px; padding-bottom: 10px;">
                    <%= form_for(@event, { :class => "form-inline", :action => "update", :method => "put"}) do |f| %>
                      <div class="field">
                        <%= f.label "Event Name" %><br>
                        <%= f.text_field :name %>
                      </div>
                      <div class="field">
                        <%= f.label "Event Date" %><br>
                        <%= f.date_select :date %>
                      </div>
                      <div class="field">
                        <%= f.label "Location" %><br>
                        <%= f.text_field :location %>
                      </div>
                      <div class="field">
                        <%= f.label "Package Type" %>
                        <%= f.select :package_type, options_for_select(["Flashy Booth", "Action Booth", "Red Carpet Event", "A-List Red Carpet"]), :selected => params[:package_type] %><br />
                      </div>
                      <div class="field">
                        <%= f.label "Make Gallery Public"%><br>
                        <%= f.check_box(:is_public, {}, true) %><br>
                      </div>
                      <div>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                      </div>
                      <div class="actions">
                       <%= f.submit "Update Event", class: "btn btn-dark" %>
                        </div>
                    <% end %>
                </div>
            </li>
            <% if current_user %>
                <li>
                    <%= link_to "SIGN OUT", session_path, method: :delete %>
                </li>
            <% else %>
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">SIGN IN <strong class="caret"></strong></a>
                    <div class="dropdown-menu" style="padding: 15px; padding-bottom: 10px;">
                        <%= form_for(@user, {url: session_path}) do |f| %>
                            <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
                            <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
                            <%= f.submit "Sign In", class: "btn btn-dark" %>
                        <% end %>
                    </div>
                </li>
            <% end %>
        </ul>
    </nav>

    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= @event.name.upcase %> GALLERY </h1>
                </div>
                <% unless @event.uploads.nil? %>         
                    <% @event.uploads.each do |a| %>
                        <div class="col-lg-3 col-md-4 col xs thumb">
                            <a data-toggle="modal" data-target="#myModal">
                                <%= image_tag(a.uploaded_file(:small), class: "img-responsive") %>
                            </a>
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="center">
                                                <%= image_tag(a.uploaded_file(:original)) %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </header>


<script>
// Closes the sidebar menu
$("#menu-close").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Opens the sidebar menu
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Scrolls to the selected menu item on the page
$(function() {
    $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html,body').animate({
                    scrollTop: target.offset().top
                }, 1000);
                return false;
            }
        }
    });
});
</script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Flash Life Photo Booth</title>
  <%= stylesheet_link_tag    'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.16/angular.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload, html: { multipart: true }) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
        <% @upload.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.collection_select(:event_id, Event.all, :id, :name, {:prompt => "Please select an event"}) %><br><br>
    <%= f.label :uploaded_file, t('.upload_new_file') %>
    <%= f.file_field :uploaded_file, multiple: true, name: 'upload[uploaded_file]' %><br>
    <%= f.submit %>
  </div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="progress-bar bar" style="width: 0%"></div></div></div></script>

app/views/uploads/_upload.html.erb
<%= image_tag(@upload.uploaded_file(:small)) %><br>
<%= image_tag(@upload.uploaded_file(:original))  %>

app/views/uploads/edit.html.erb
<body>
<header class="header">
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>
</header>
</body>

app/views/uploads/index.html.erb
<header class="header">
<h1 class="page-header">FLASH LIFE UPLOADS</h1>
<div class="table-responsive"%>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Event ID</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th></th>
        <th></th>
        <th></tH>
      </tr>
    </thead>

    <tbody>
      <% @uploads.each do |upload| %>
        <tr>
          <td><%= upload.event_id %></td>
          <td><%= upload.created_at%></td>
          <td><%= upload.updated_at%></td>
          <td><%= link_to 'Show', upload %></td>
          <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
          <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Upload', new_upload_path %>
</header>

app/views/uploads/new.html.erb
<body>
<header class="header">
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>
</header>
</body>

app/views/uploads/show.html.erb
<body>
<header class="header">
<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>


<br />
<%= render 'upload' %>
<br />

</header>
</body>

app/views/users/index.html.erb
<body>
<!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <% if current_user %>
                    <%= link_to "WELCOME" + " #{current_user.first_name.upcase}", user_path(current_user) %>
                <% else %>
                    <a href="#top">FLASH LIFE PHOTO BOOTH</a>
                <% end %>
            </li>
            <% if current_user %>
                <li>
                    <%= link_to "SIGN OUT", session_path, method: :delete %>
                </li>
            <% else %>
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">SIGN IN <strong class="caret"></strong></a>
                    <div class="dropdown-menu" style="padding: 15px; padding-bottom: 10px;">
                        <%= form_for(@user, {url: session_path}) do |f| %>
                            <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
                            <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
                            <%= f.submit "Sign In", class: "btn btn-dark" %>
                        <% end %>
                    </div>
                </li>
            <% end %>
        </ul>
    </nav>
<header class="header">
<div class="container-fluid"> 
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">

        <h2>USER LIST</h2>
            <div class="table-responsive table-condensed">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Address</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |user| %>
                    <tr>
                      <td><%= user.first_name %></td>
                      <td><%= user.last_name%></td>
                      <td><%= user.email %></td>
                      <td><%= user.phone_number %></td>
                      <td><%= user.address %></td>
                      <td><%= link_to 'Show', user %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <br>
            </div>
        </div>
    </div>
</div>
</header>
<script>

// Closes the sidebar menu
$("#menu-close").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Opens the sidebar menu
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Scrolls to the selected menu item on the page
$(function() {
    $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html,body').animate({
                    scrollTop: target.offset().top
                }, 1000);
                return false;
            }
        }
    });
});
</script>
</body>

app/views/users/show.html.erb
<body> 
 
 <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <% if current_user %>
                    <%= link_to "WELCOME" + " #{current_user.first_name.upcase}", user_path(current_user) %>
                <% else %>
                    <a href="#top">FLASH LIFE PHOTO BOOTH</a>
                <% end %>
            </li>
            <% if current_user %>
                <li>
                    <%= link_to "SIGN OUT", session_path, method: :delete %>
                </li>
            <% else %>
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">SIGN IN <strong class="caret"></strong></a>
                    <div class="dropdown-menu" style="padding: 15px; padding-bottom: 10px;">
                        <%= form_for(@user, {url: session_path}) do |f| %>
                            <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
                            <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
                            <%= f.submit "Sign In", class: "btn btn-dark" %>
                        <% end %>
                    </div>
                </li>
            <% end %>
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">EDIT ACCOUNT<strong class="caret"></strong></a>
                <div class="dropdown-menu" style="padding: 15px; padding-bottom: 10px;">
                    <%= form_for(@user, { :class => "form-inline", :action => "update", :method => "put"}) do |f| %>
                            <div class="field">
                              <%= f.label "First Name" %>
                              <%= f.text_field :first_name, class: "form-control" %>
                            </div>
                            <div class="field">
                              <%= f.label "Last Name" %>
                              <%= f.text_field :last_name, class: "form-control" %>
                            </div>
                            <div class="field">
                              <%= f.label "Mailing Address" %><br>
                              <%= f.text_field :address, class: "form-control" %>
                            </div>
                            <div class="field">
                              <%= f.label "Phone Number" %><br>
                              <%= f.text_field :phone_number, class: "form-control" %>
                            </div>
                            <div class="field">
                              <%= f.label "Email" %><br>
                              <%= f.text_field :email, class: "form-control" %>
                            </div> 
                            <div class="field">
                              <%= f.label "Password" %><br>
                              <%= f.password_field :password, class: "form-control" %>
                            </div>
                            <div class="field">
                              <%= f.label "Confirm Password" %><br>
                              <%= f.password_field :password_confirmation, class: "form-control" %>
                            </div>
                            <div class="actions">
                              <%= f.submit "Update Account", class: "btn btn-dark" %>
                            </div>
                    <% end %>
            </li>
          <!--   <li>
                <a href="#about">ABOUT</a>
            </li>
            <li>
                <a href="#packages">PACKAGES</a>
            </li>
            <li>
                <a href="#gallery">GALLERY</a>
            </li>
            <li>
                <a href="#contact">CONTACT</a>
            </li> -->
            
        </ul>
    </nav>

<header class="header">
  <div class="container-fluid"> 
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
        <h2> My Events </h2>
            <% if @user.events.count != 0 %>
    	   <div class="table-responsive">
        		<table class="table table-hover">
        		  <thead>
        		    <tr>
        		      <th>Event Name</th>
        		      <th>Date</th>
        		      <th>Location</th>
        		      <th>Package Type</th>
        		      <th></th>
        		    </tr>
        		  </thead>
        		  <tbody>
        		    <% @user.events.each do |event| %>
        		      <tr>
        		        <td><%= event.name %></td>
        		        <td><%= event.date %></td>
        		        <td><%= event.location %></td>
        		        <td><%= event.package_type %></td>
        		        <td><%= link_to 'Show', event %></td>
        		      </tr>
        		    <% end %>
        			</tbody>
        		</table>
        		<br>
        	</div>
            <% else %>
            <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <div class="center">
            <button class="btn btn-dark btn-lg" data-toggle="modal" data-target="#myModalEvent">Create Event</button>
      <!-- Modal -->
      <div class="modal fade" id="myModalEvent" tabindex="-1" role="dialog" aria-labelledby="myModalLabelEvent" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabelEvent">CREATE EVENT</h4>
          </div>
          <div class="modal-body">
            <%= form_for(@event, { :class => "form-inline", :action => "create", :method => "post"}) do |f| %>
              <div class="field">
                <%= f.label "Event Name" %><br>
                <%= f.text_field :name %>
              </div>
              <div class="field">
                <%= f.label "Event Date" %><br>
                <%= f.date_select :date %>
              </div>
              <div class="field">
                <%= f.label "Location" %><br>
                <%= f.text_field :location %>
              </div>
              <div class="field">
                <%= f.label "Package Type" %>
                <%= f.select :package_type, options_for_select(["Flashy Booth", "Action Booth", "Red Carpet Event", "A-List Red Carpet"]), :selected => params[:package_type] %><br />
              </div>
              <div class="field">
                <%= f.label "Make Gallery Public"%><br>
                <%= f.check_box(:is_public, {}, true) %><br>
              </div>
                <%= f.hidden_field :user_id, value: current_user.id %>
          </div>
          <div class="modal-footer">
            <div class="actions">
                <%= f.submit "Create Event", class: "btn btn-dark" %>
            </div>
            <% end %>
          </div>
            <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
        </div>
      </div>
      </div>
      </div>
        </div>
      </div>
    </div>
</header>
<script>

// Closes the sidebar menu
$("#menu-close").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Opens the sidebar menu
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Scrolls to the selected menu item on the page
$(function() {
    $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html,body').animate({
                    scrollTop: target.offset().top
                }, 1000);
                return false;
            }
        }
    });
});
</script>

</body>